title: "LemanTh — Lausanne Event on Machine Learning and Neural Network Theory"
description: "Third edition of LemanTh: a focused meeting on ML & Neural Network Theory in Lausanne"
url: "https://<YOUR_GITHUB_USERNAME>.github.io"
baseurl: "/<YOUR_REPO_NAME>"
# If repo is user/organization pages (username.github.io), set baseurl: "" and url to your pages URL

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"  # skins: air, aqua, contrast, dark, dirt, neon, mint, sunrise, default

# Plugins enabled by GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Global defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: false

# Navigation
# Edit labels/links as you like
nav:
  - title: "Home"
    url: /
  - title: "Speakers"
    url: /pages/speakers/
  - title: "Schedule"
    url: /pages/schedule/
  - title: "Registration"
    url: /pages/registration/
  - title: "Venue"
    url: /pages/venue/
  - title: "Code of Conduct"
    url: /pages/conduct/

# Social / metadata
logo: /assets/img/lemanth-logo.png
favicon: /assets/img/favicon.png
seo:
  type: Event
  name: "LemanTh — Lausanne Event on Machine Learning and Neural Network Theory"
  same_as:
    - https://lemanth2024.github.io
    - https://lemanth2025.github.io

# Custom variables
event:
  name: "LemanTh — Lausanne Event on Machine Learning and Neural Network Theory"
  short: "LemanTh"
  dates: "TBD, 2026"  # edit
  location: "EPFL, Lausanne"  # edit
  registration_url: "https://forms.gle/XXXX"  # edit
  contact_email: "organizers@lemanth.org"  # edit
  countdown_deadline: "2026-06-15T08:30:00+02:00"  # edit (ISO8601, Europe/Paris)